### ISSUE TITLE
pre-commit autoupdate tries to change from v1.3 to v1.1

### ISSUE THREAD

**Issue by underyx** [humitos/mirrors-autoflake#6]
```
$ pre-commit autoupdate
Updating https://github.com/humitos/mirrors-autoflake ... updating v1.3 -> v1.1.
```

I'm not sure why this is happening when using the following configuration, but I assumed it's more likely to be an issue with the state of this repo than with the autoupdate logic.

```yaml
  - repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.3
    hooks:
      - id: autoflake
        args: [--in-place]
```
